micronaut:
  application:
    name: tasksStorage
# TODO: finalize user and password values
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/tasks_store?createDatabaseIfNotExist=true`}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${DBC_USER:postgres}
    password: ${JDBC_PASSWORD:secretPassword}

# TODO: auto create database
jpa.default.properties:
  hibernate:
    hbm2ddl:
      # more info at: https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl
      # Update the database schema
      auto: create-drop
    # Echo all executed SQL commands to stdout
    show_dql: true
